### PR TITLE
Add unit tests for the image

### PR DESCRIPTION
**Pull request by huseyin**
Changes:
- [bats](https://github.com/sstephenson/bats) was used for the tests
- Makefile was used to build image and run the tests

### CODE REVIEW

**Review by szkl — APPROVED** [review]

**Comment by szkl** [comment]
@htaslan thanks for the pull request. This is very good. I'll approve this change set but I have some alternative ideas to your implementation. I'd like to discuss it here.

I'd like to have bats installed into a container instead of to host system. A release tarball or revision archive would be better than cloning entire repository. All the tests require running a container and shutting it down. It would be better to start a single container install bats and run all the tests and exit in my opinion.

**Comment by huseyin** [comment]
Thanks for merging. I agree with you. It was my first thought.

alternative can be as follows:

- run container (with `detach` option)
- exec command in container
- wait container
- kill container
- rm container

But all of them already can be done with the `--rm` flag. Also, the number of tests is too few. I don't think there will be much performance difference. So I didn't want to manage the logic I wrote  above in the helper file.  But it's no problem. Tests can be easily adapted to the above steps.

[I'm thinking out loud]

- add "run container func" into helper
- add "exec command func" into helper
- add "rm container func" into helper
- add "rm container" as final test to bats file (because this operation cannot be done in the helper script)

I don't agree with you about install bats into a container. All tests must be performed on the host system. Perhaps an option to install bats on the host system can be added. Or docker bats image can be used. but i couldn't find any stable bats image.

**Comment by szkl** [comment]
I agree with run && exec && kill && rm workflow. We are going to unify all image definitions soon. We were thinking something like this test suite to ensure images are built correctly. It makes sense for me to run a single container instead of one-per-test. These tests will be eventually run by a CI platform where how many containers you can run be limited.

All tests are technically performed in the container. The host system is just invoking it. Therefore, it makes sense not to install bats into the host system.

On the other hand, I think it would provide a more general If we test suite doesn't run containers but execute tests directly. We could use these test suites to check dependencies and requirements are satisfied on any system that is meant to run koding.

**Comment by huseyin** [comment]
If there is such a thought, take a look at [goss](http://goss.rocks). I haven't used goss. because I have reasons.  I can explain reasons.
> We are going to unify all image definitions soon. We were thinking something like this test suite to ensure images are built correctly.

i agree. 
> All tests are technically performed in the container. The host system is just invoking it. Therefore, it makes sense not to install bats into the host system.

Using CI will solve many problems. But we are obliged this at this stage. Because we doesn't have a CI tool. But this is not the case in the future.
> On the other hand, I think it would provide a more general If we test suite doesn't run containers but execute tests directly.

Yes, maybe it should be this way.
> run && exec && kill && rm workflow.

**Pull request merged**
